# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pricing.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'pricing.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpricing.proto\"c\n\x0cPricingInput\x12\x18\n\x04past\x18\x01 \x03(\x0b\x32\n.PastLines\x12\x1d\n\x15monitoringDateReached\x18\x02 \x01(\x08\x12\x0c\n\x04time\x18\x03 \x01(\x01\x12\x0c\n\x04json\x18\x04 \x01(\t\"\x1a\n\tPastLines\x12\r\n\x05value\x18\x01 \x03(\x01\"Y\n\rPricingOutput\x12\r\n\x05price\x18\x01 \x01(\x01\x12\x0e\n\x06\x64\x65ltas\x18\x02 \x03(\x01\x12\x13\n\x0bpriceStdDev\x18\x03 \x01(\x01\x12\x14\n\x0c\x64\x65ltasStdDev\x18\x04 \x03(\x01\"\x07\n\x05\x45mpty\"_\n\x07ReqInfo\x12\x1c\n\x14\x64omesticInterestRate\x18\x01 \x01(\x01\x12$\n\x1crelativeFiniteDifferenceStep\x18\x02 \x01(\x01\x12\x10\n\x08sampleNb\x18\x03 \x01(\x05\x32\\\n\nGrpcPricer\x12/\n\x0ePriceAndDeltas\x12\r.PricingInput\x1a\x0e.PricingOutput\x12\x1d\n\tHeartbeat\x12\x06.Empty\x1a\x08.ReqInfoB\x15\xaa\x02\x12GrpcPricing.Protosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pricing_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\022GrpcPricing.Protos'
  _globals['_PRICINGINPUT']._serialized_start=17
  _globals['_PRICINGINPUT']._serialized_end=116
  _globals['_PASTLINES']._serialized_start=118
  _globals['_PASTLINES']._serialized_end=144
  _globals['_PRICINGOUTPUT']._serialized_start=146
  _globals['_PRICINGOUTPUT']._serialized_end=235
  _globals['_EMPTY']._serialized_start=237
  _globals['_EMPTY']._serialized_end=244
  _globals['_REQINFO']._serialized_start=246
  _globals['_REQINFO']._serialized_end=341
  _globals['_GRPCPRICER']._serialized_start=343
  _globals['_GRPCPRICER']._serialized_end=435
# @@protoc_insertion_point(module_scope)
