// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client/pricing.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_client_2fpricing_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_client_2fpricing_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4023000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4023004 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_bases.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_client_2fpricing_2eproto

PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_client_2fpricing_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable
    descriptor_table_client_2fpricing_2eproto;
class Empty;
struct EmptyDefaultTypeInternal;
extern EmptyDefaultTypeInternal _Empty_default_instance_;
class PastLines;
struct PastLinesDefaultTypeInternal;
extern PastLinesDefaultTypeInternal _PastLines_default_instance_;
class PricingInput;
struct PricingInputDefaultTypeInternal;
extern PricingInputDefaultTypeInternal _PricingInput_default_instance_;
class PricingOutput;
struct PricingOutputDefaultTypeInternal;
extern PricingOutputDefaultTypeInternal _PricingOutput_default_instance_;
class ReqInfo;
struct ReqInfoDefaultTypeInternal;
extern ReqInfoDefaultTypeInternal _ReqInfo_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template <>
::Empty* Arena::CreateMaybeMessage<::Empty>(Arena*);
template <>
::PastLines* Arena::CreateMaybeMessage<::PastLines>(Arena*);
template <>
::PricingInput* Arena::CreateMaybeMessage<::PricingInput>(Arena*);
template <>
::PricingOutput* Arena::CreateMaybeMessage<::PricingOutput>(Arena*);
template <>
::ReqInfo* Arena::CreateMaybeMessage<::ReqInfo>(Arena*);
PROTOBUF_NAMESPACE_CLOSE


// ===================================================================


// -------------------------------------------------------------------

class PricingInput final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:PricingInput) */ {
 public:
  inline PricingInput() : PricingInput(nullptr) {}
  ~PricingInput() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR PricingInput(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PricingInput(const PricingInput& from);
  PricingInput(PricingInput&& from) noexcept
    : PricingInput() {
    *this = ::std::move(from);
  }

  inline PricingInput& operator=(const PricingInput& from) {
    CopyFrom(from);
    return *this;
  }
  inline PricingInput& operator=(PricingInput&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PricingInput& default_instance() {
    return *internal_default_instance();
  }
  static inline const PricingInput* internal_default_instance() {
    return reinterpret_cast<const PricingInput*>(
               &_PricingInput_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(PricingInput& a, PricingInput& b) {
    a.Swap(&b);
  }
  inline void Swap(PricingInput* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PricingInput* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PricingInput* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PricingInput>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PricingInput& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PricingInput& from) {
    PricingInput::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PricingInput* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "PricingInput";
  }
  protected:
  explicit PricingInput(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPastFieldNumber = 1,
    kJsonFieldNumber = 4,
    kTimeFieldNumber = 3,
    kMonitoringDateReachedFieldNumber = 2,
  };
  // repeated .PastLines past = 1;
  int past_size() const;
  private:
  int _internal_past_size() const;

  public:
  void clear_past() ;
  ::PastLines* mutable_past(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PastLines >*
      mutable_past();
  private:
  const ::PastLines& _internal_past(int index) const;
  ::PastLines* _internal_add_past();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<::PastLines>& _internal_past() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<::PastLines>* _internal_mutable_past();
  public:
  const ::PastLines& past(int index) const;
  ::PastLines* add_past();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PastLines >&
      past() const;
  // string json = 4;
  void clear_json() ;
  const std::string& json() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_json(Arg_&& arg, Args_... args);
  std::string* mutable_json();
  PROTOBUF_NODISCARD std::string* release_json();
  void set_allocated_json(std::string* ptr);

  private:
  const std::string& _internal_json() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_json(
      const std::string& value);
  std::string* _internal_mutable_json();

  public:
  // double time = 3;
  void clear_time() ;
  double time() const;
  void set_time(double value);

  private:
  double _internal_time() const;
  void _internal_set_time(double value);

  public:
  // bool monitoringDateReached = 2;
  void clear_monitoringdatereached() ;
  bool monitoringdatereached() const;
  void set_monitoringdatereached(bool value);

  private:
  bool _internal_monitoringdatereached() const;
  void _internal_set_monitoringdatereached(bool value);

  public:
  // @@protoc_insertion_point(class_scope:PricingInput)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PastLines > past_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr json_;
    double time_;
    bool monitoringdatereached_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_client_2fpricing_2eproto;
};// -------------------------------------------------------------------

class PastLines final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:PastLines) */ {
 public:
  inline PastLines() : PastLines(nullptr) {}
  ~PastLines() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR PastLines(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PastLines(const PastLines& from);
  PastLines(PastLines&& from) noexcept
    : PastLines() {
    *this = ::std::move(from);
  }

  inline PastLines& operator=(const PastLines& from) {
    CopyFrom(from);
    return *this;
  }
  inline PastLines& operator=(PastLines&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PastLines& default_instance() {
    return *internal_default_instance();
  }
  static inline const PastLines* internal_default_instance() {
    return reinterpret_cast<const PastLines*>(
               &_PastLines_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(PastLines& a, PastLines& b) {
    a.Swap(&b);
  }
  inline void Swap(PastLines* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PastLines* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PastLines* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PastLines>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PastLines& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PastLines& from) {
    PastLines::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PastLines* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "PastLines";
  }
  protected:
  explicit PastLines(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kValueFieldNumber = 1,
  };
  // repeated double value = 1;
  int value_size() const;
  private:
  int _internal_value_size() const;

  public:
  void clear_value() ;
  double value(int index) const;
  void set_value(int index, double value);
  void add_value(double value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField<double>& value() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField<double>* mutable_value();

  private:
  double _internal_value(int index) const;
  void _internal_add_value(double value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField<double>& _internal_value() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField<double>* _internal_mutable_value();

  public:
  // @@protoc_insertion_point(class_scope:PastLines)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedField<double> value_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_client_2fpricing_2eproto;
};// -------------------------------------------------------------------

class PricingOutput final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:PricingOutput) */ {
 public:
  inline PricingOutput() : PricingOutput(nullptr) {}
  ~PricingOutput() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR PricingOutput(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PricingOutput(const PricingOutput& from);
  PricingOutput(PricingOutput&& from) noexcept
    : PricingOutput() {
    *this = ::std::move(from);
  }

  inline PricingOutput& operator=(const PricingOutput& from) {
    CopyFrom(from);
    return *this;
  }
  inline PricingOutput& operator=(PricingOutput&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PricingOutput& default_instance() {
    return *internal_default_instance();
  }
  static inline const PricingOutput* internal_default_instance() {
    return reinterpret_cast<const PricingOutput*>(
               &_PricingOutput_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(PricingOutput& a, PricingOutput& b) {
    a.Swap(&b);
  }
  inline void Swap(PricingOutput* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PricingOutput* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PricingOutput* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PricingOutput>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PricingOutput& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PricingOutput& from) {
    PricingOutput::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PricingOutput* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "PricingOutput";
  }
  protected:
  explicit PricingOutput(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDeltasFieldNumber = 2,
    kDeltasStdDevFieldNumber = 4,
    kPriceFieldNumber = 1,
    kPriceStdDevFieldNumber = 3,
  };
  // repeated double deltas = 2;
  int deltas_size() const;
  private:
  int _internal_deltas_size() const;

  public:
  void clear_deltas() ;
  double deltas(int index) const;
  void set_deltas(int index, double value);
  void add_deltas(double value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField<double>& deltas() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField<double>* mutable_deltas();

  private:
  double _internal_deltas(int index) const;
  void _internal_add_deltas(double value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField<double>& _internal_deltas() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField<double>* _internal_mutable_deltas();

  public:
  // repeated double deltasStdDev = 4;
  int deltasstddev_size() const;
  private:
  int _internal_deltasstddev_size() const;

  public:
  void clear_deltasstddev() ;
  double deltasstddev(int index) const;
  void set_deltasstddev(int index, double value);
  void add_deltasstddev(double value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField<double>& deltasstddev() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField<double>* mutable_deltasstddev();

  private:
  double _internal_deltasstddev(int index) const;
  void _internal_add_deltasstddev(double value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField<double>& _internal_deltasstddev() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField<double>* _internal_mutable_deltasstddev();

  public:
  // double price = 1;
  void clear_price() ;
  double price() const;
  void set_price(double value);

  private:
  double _internal_price() const;
  void _internal_set_price(double value);

  public:
  // double priceStdDev = 3;
  void clear_pricestddev() ;
  double pricestddev() const;
  void set_pricestddev(double value);

  private:
  double _internal_pricestddev() const;
  void _internal_set_pricestddev(double value);

  public:
  // @@protoc_insertion_point(class_scope:PricingOutput)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedField<double> deltas_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedField<double> deltasstddev_;
    double price_;
    double pricestddev_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_client_2fpricing_2eproto;
};// -------------------------------------------------------------------

class Empty final :
    public ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase /* @@protoc_insertion_point(class_definition:Empty) */ {
 public:
  inline Empty() : Empty(nullptr) {}
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR Empty(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Empty(const Empty& from);
  Empty(Empty&& from) noexcept
    : Empty() {
    *this = ::std::move(from);
  }

  inline Empty& operator=(const Empty& from) {
    CopyFrom(from);
    return *this;
  }
  inline Empty& operator=(Empty&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Empty& default_instance() {
    return *internal_default_instance();
  }
  static inline const Empty* internal_default_instance() {
    return reinterpret_cast<const Empty*>(
               &_Empty_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(Empty& a, Empty& b) {
    a.Swap(&b);
  }
  inline void Swap(Empty* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Empty* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Empty* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Empty>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const Empty& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const Empty& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }
  public:

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "Empty";
  }
  protected:
  explicit Empty(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:Empty)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
  };
  friend struct ::TableStruct_client_2fpricing_2eproto;
};// -------------------------------------------------------------------

class ReqInfo final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ReqInfo) */ {
 public:
  inline ReqInfo() : ReqInfo(nullptr) {}
  ~ReqInfo() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR ReqInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ReqInfo(const ReqInfo& from);
  ReqInfo(ReqInfo&& from) noexcept
    : ReqInfo() {
    *this = ::std::move(from);
  }

  inline ReqInfo& operator=(const ReqInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline ReqInfo& operator=(ReqInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ReqInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const ReqInfo* internal_default_instance() {
    return reinterpret_cast<const ReqInfo*>(
               &_ReqInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(ReqInfo& a, ReqInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(ReqInfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ReqInfo* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ReqInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ReqInfo>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ReqInfo& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ReqInfo& from) {
    ReqInfo::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ReqInfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "ReqInfo";
  }
  protected:
  explicit ReqInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDomesticInterestRateFieldNumber = 1,
    kRelativeFiniteDifferenceStepFieldNumber = 2,
    kSampleNbFieldNumber = 3,
  };
  // double domesticInterestRate = 1;
  void clear_domesticinterestrate() ;
  double domesticinterestrate() const;
  void set_domesticinterestrate(double value);

  private:
  double _internal_domesticinterestrate() const;
  void _internal_set_domesticinterestrate(double value);

  public:
  // double relativeFiniteDifferenceStep = 2;
  void clear_relativefinitedifferencestep() ;
  double relativefinitedifferencestep() const;
  void set_relativefinitedifferencestep(double value);

  private:
  double _internal_relativefinitedifferencestep() const;
  void _internal_set_relativefinitedifferencestep(double value);

  public:
  // int32 sampleNb = 3;
  void clear_samplenb() ;
  ::int32_t samplenb() const;
  void set_samplenb(::int32_t value);

  private:
  ::int32_t _internal_samplenb() const;
  void _internal_set_samplenb(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:ReqInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    double domesticinterestrate_;
    double relativefinitedifferencestep_;
    ::int32_t samplenb_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_client_2fpricing_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// PricingInput

// repeated .PastLines past = 1;
inline int PricingInput::_internal_past_size() const {
  return _impl_.past_.size();
}
inline int PricingInput::past_size() const {
  return _internal_past_size();
}
inline void PricingInput::clear_past() {
  _internal_mutable_past()->Clear();
}
inline ::PastLines* PricingInput::mutable_past(int index) {
  // @@protoc_insertion_point(field_mutable:PricingInput.past)
  return _internal_mutable_past()->Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PastLines >*
PricingInput::mutable_past() {
  // @@protoc_insertion_point(field_mutable_list:PricingInput.past)
  return _internal_mutable_past();
}
inline const ::PastLines& PricingInput::_internal_past(int index) const {
  return _internal_past().Get(index);
}
inline const ::PastLines& PricingInput::past(int index) const {
  // @@protoc_insertion_point(field_get:PricingInput.past)
  return _internal_past(index);
}
inline ::PastLines* PricingInput::_internal_add_past() {
  return _internal_mutable_past()->Add();
}
inline ::PastLines* PricingInput::add_past() {
  ::PastLines* _add = _internal_add_past();
  // @@protoc_insertion_point(field_add:PricingInput.past)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PastLines >&
PricingInput::past() const {
  // @@protoc_insertion_point(field_list:PricingInput.past)
  return _internal_past();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<::PastLines>&
PricingInput::_internal_past() const {
  return _impl_.past_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<::PastLines>*
PricingInput::_internal_mutable_past() {
  return &_impl_.past_;
}

// bool monitoringDateReached = 2;
inline void PricingInput::clear_monitoringdatereached() {
  _impl_.monitoringdatereached_ = false;
}
inline bool PricingInput::monitoringdatereached() const {
  // @@protoc_insertion_point(field_get:PricingInput.monitoringDateReached)
  return _internal_monitoringdatereached();
}
inline void PricingInput::set_monitoringdatereached(bool value) {
  _internal_set_monitoringdatereached(value);
  // @@protoc_insertion_point(field_set:PricingInput.monitoringDateReached)
}
inline bool PricingInput::_internal_monitoringdatereached() const {
  return _impl_.monitoringdatereached_;
}
inline void PricingInput::_internal_set_monitoringdatereached(bool value) {
  ;
  _impl_.monitoringdatereached_ = value;
}

// double time = 3;
inline void PricingInput::clear_time() {
  _impl_.time_ = 0;
}
inline double PricingInput::time() const {
  // @@protoc_insertion_point(field_get:PricingInput.time)
  return _internal_time();
}
inline void PricingInput::set_time(double value) {
  _internal_set_time(value);
  // @@protoc_insertion_point(field_set:PricingInput.time)
}
inline double PricingInput::_internal_time() const {
  return _impl_.time_;
}
inline void PricingInput::_internal_set_time(double value) {
  ;
  _impl_.time_ = value;
}

// string json = 4;
inline void PricingInput::clear_json() {
  _impl_.json_.ClearToEmpty();
}
inline const std::string& PricingInput::json() const {
  // @@protoc_insertion_point(field_get:PricingInput.json)
  return _internal_json();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void PricingInput::set_json(Arg_&& arg,
                                                     Args_... args) {
  ;
  _impl_.json_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:PricingInput.json)
}
inline std::string* PricingInput::mutable_json() {
  std::string* _s = _internal_mutable_json();
  // @@protoc_insertion_point(field_mutable:PricingInput.json)
  return _s;
}
inline const std::string& PricingInput::_internal_json() const {
  return _impl_.json_.Get();
}
inline void PricingInput::_internal_set_json(const std::string& value) {
  ;


  _impl_.json_.Set(value, GetArenaForAllocation());
}
inline std::string* PricingInput::_internal_mutable_json() {
  ;
  return _impl_.json_.Mutable( GetArenaForAllocation());
}
inline std::string* PricingInput::release_json() {
  // @@protoc_insertion_point(field_release:PricingInput.json)
  return _impl_.json_.Release();
}
inline void PricingInput::set_allocated_json(std::string* value) {
  _impl_.json_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.json_.IsDefault()) {
          _impl_.json_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:PricingInput.json)
}

// -------------------------------------------------------------------

// PastLines

// repeated double value = 1;
inline int PastLines::_internal_value_size() const {
  return _impl_.value_.size();
}
inline int PastLines::value_size() const {
  return _internal_value_size();
}
inline void PastLines::clear_value() {
  _internal_mutable_value()->Clear();
}
inline double PastLines::value(int index) const {
  // @@protoc_insertion_point(field_get:PastLines.value)
  return _internal_value(index);
}
inline void PastLines::set_value(int index, double value) {
  _internal_mutable_value()->Set(index, value);
  // @@protoc_insertion_point(field_set:PastLines.value)
}
inline void PastLines::add_value(double value) {
  _internal_add_value(value);
  // @@protoc_insertion_point(field_add:PastLines.value)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField<double>& PastLines::value() const {
  // @@protoc_insertion_point(field_list:PastLines.value)
  return _internal_value();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField<double>* PastLines::mutable_value() {
  // @@protoc_insertion_point(field_mutable_list:PastLines.value)
  return _internal_mutable_value();
}

inline double PastLines::_internal_value(int index) const {
  return _internal_value().Get(index);
}
inline void PastLines::_internal_add_value(double value) {
  _internal_mutable_value()->Add(value);
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField<double>& PastLines::_internal_value() const {
  return _impl_.value_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField<double>* PastLines::_internal_mutable_value() {
  return &_impl_.value_;
}

// -------------------------------------------------------------------

// PricingOutput

// double price = 1;
inline void PricingOutput::clear_price() {
  _impl_.price_ = 0;
}
inline double PricingOutput::price() const {
  // @@protoc_insertion_point(field_get:PricingOutput.price)
  return _internal_price();
}
inline void PricingOutput::set_price(double value) {
  _internal_set_price(value);
  // @@protoc_insertion_point(field_set:PricingOutput.price)
}
inline double PricingOutput::_internal_price() const {
  return _impl_.price_;
}
inline void PricingOutput::_internal_set_price(double value) {
  ;
  _impl_.price_ = value;
}

// repeated double deltas = 2;
inline int PricingOutput::_internal_deltas_size() const {
  return _impl_.deltas_.size();
}
inline int PricingOutput::deltas_size() const {
  return _internal_deltas_size();
}
inline void PricingOutput::clear_deltas() {
  _internal_mutable_deltas()->Clear();
}
inline double PricingOutput::deltas(int index) const {
  // @@protoc_insertion_point(field_get:PricingOutput.deltas)
  return _internal_deltas(index);
}
inline void PricingOutput::set_deltas(int index, double value) {
  _internal_mutable_deltas()->Set(index, value);
  // @@protoc_insertion_point(field_set:PricingOutput.deltas)
}
inline void PricingOutput::add_deltas(double value) {
  _internal_add_deltas(value);
  // @@protoc_insertion_point(field_add:PricingOutput.deltas)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField<double>& PricingOutput::deltas() const {
  // @@protoc_insertion_point(field_list:PricingOutput.deltas)
  return _internal_deltas();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField<double>* PricingOutput::mutable_deltas() {
  // @@protoc_insertion_point(field_mutable_list:PricingOutput.deltas)
  return _internal_mutable_deltas();
}

inline double PricingOutput::_internal_deltas(int index) const {
  return _internal_deltas().Get(index);
}
inline void PricingOutput::_internal_add_deltas(double value) {
  _internal_mutable_deltas()->Add(value);
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField<double>& PricingOutput::_internal_deltas() const {
  return _impl_.deltas_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField<double>* PricingOutput::_internal_mutable_deltas() {
  return &_impl_.deltas_;
}

// double priceStdDev = 3;
inline void PricingOutput::clear_pricestddev() {
  _impl_.pricestddev_ = 0;
}
inline double PricingOutput::pricestddev() const {
  // @@protoc_insertion_point(field_get:PricingOutput.priceStdDev)
  return _internal_pricestddev();
}
inline void PricingOutput::set_pricestddev(double value) {
  _internal_set_pricestddev(value);
  // @@protoc_insertion_point(field_set:PricingOutput.priceStdDev)
}
inline double PricingOutput::_internal_pricestddev() const {
  return _impl_.pricestddev_;
}
inline void PricingOutput::_internal_set_pricestddev(double value) {
  ;
  _impl_.pricestddev_ = value;
}

// repeated double deltasStdDev = 4;
inline int PricingOutput::_internal_deltasstddev_size() const {
  return _impl_.deltasstddev_.size();
}
inline int PricingOutput::deltasstddev_size() const {
  return _internal_deltasstddev_size();
}
inline void PricingOutput::clear_deltasstddev() {
  _internal_mutable_deltasstddev()->Clear();
}
inline double PricingOutput::deltasstddev(int index) const {
  // @@protoc_insertion_point(field_get:PricingOutput.deltasStdDev)
  return _internal_deltasstddev(index);
}
inline void PricingOutput::set_deltasstddev(int index, double value) {
  _internal_mutable_deltasstddev()->Set(index, value);
  // @@protoc_insertion_point(field_set:PricingOutput.deltasStdDev)
}
inline void PricingOutput::add_deltasstddev(double value) {
  _internal_add_deltasstddev(value);
  // @@protoc_insertion_point(field_add:PricingOutput.deltasStdDev)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField<double>& PricingOutput::deltasstddev() const {
  // @@protoc_insertion_point(field_list:PricingOutput.deltasStdDev)
  return _internal_deltasstddev();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField<double>* PricingOutput::mutable_deltasstddev() {
  // @@protoc_insertion_point(field_mutable_list:PricingOutput.deltasStdDev)
  return _internal_mutable_deltasstddev();
}

inline double PricingOutput::_internal_deltasstddev(int index) const {
  return _internal_deltasstddev().Get(index);
}
inline void PricingOutput::_internal_add_deltasstddev(double value) {
  _internal_mutable_deltasstddev()->Add(value);
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField<double>& PricingOutput::_internal_deltasstddev() const {
  return _impl_.deltasstddev_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField<double>* PricingOutput::_internal_mutable_deltasstddev() {
  return &_impl_.deltasstddev_;
}

// -------------------------------------------------------------------

// Empty

// -------------------------------------------------------------------

// ReqInfo

// double domesticInterestRate = 1;
inline void ReqInfo::clear_domesticinterestrate() {
  _impl_.domesticinterestrate_ = 0;
}
inline double ReqInfo::domesticinterestrate() const {
  // @@protoc_insertion_point(field_get:ReqInfo.domesticInterestRate)
  return _internal_domesticinterestrate();
}
inline void ReqInfo::set_domesticinterestrate(double value) {
  _internal_set_domesticinterestrate(value);
  // @@protoc_insertion_point(field_set:ReqInfo.domesticInterestRate)
}
inline double ReqInfo::_internal_domesticinterestrate() const {
  return _impl_.domesticinterestrate_;
}
inline void ReqInfo::_internal_set_domesticinterestrate(double value) {
  ;
  _impl_.domesticinterestrate_ = value;
}

// double relativeFiniteDifferenceStep = 2;
inline void ReqInfo::clear_relativefinitedifferencestep() {
  _impl_.relativefinitedifferencestep_ = 0;
}
inline double ReqInfo::relativefinitedifferencestep() const {
  // @@protoc_insertion_point(field_get:ReqInfo.relativeFiniteDifferenceStep)
  return _internal_relativefinitedifferencestep();
}
inline void ReqInfo::set_relativefinitedifferencestep(double value) {
  _internal_set_relativefinitedifferencestep(value);
  // @@protoc_insertion_point(field_set:ReqInfo.relativeFiniteDifferenceStep)
}
inline double ReqInfo::_internal_relativefinitedifferencestep() const {
  return _impl_.relativefinitedifferencestep_;
}
inline void ReqInfo::_internal_set_relativefinitedifferencestep(double value) {
  ;
  _impl_.relativefinitedifferencestep_ = value;
}

// int32 sampleNb = 3;
inline void ReqInfo::clear_samplenb() {
  _impl_.samplenb_ = 0;
}
inline ::int32_t ReqInfo::samplenb() const {
  // @@protoc_insertion_point(field_get:ReqInfo.sampleNb)
  return _internal_samplenb();
}
inline void ReqInfo::set_samplenb(::int32_t value) {
  _internal_set_samplenb(value);
  // @@protoc_insertion_point(field_set:ReqInfo.sampleNb)
}
inline ::int32_t ReqInfo::_internal_samplenb() const {
  return _impl_.samplenb_;
}
inline void ReqInfo::_internal_set_samplenb(::int32_t value) {
  ;
  _impl_.samplenb_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_client_2fpricing_2eproto_2epb_2eh
