// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: pricing.proto

#include "pricing.pb.h"
#include "pricing.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>

static const char* GrpcPricer_method_names[] = {
  "/GrpcPricer/PriceAndDeltas",
  "/GrpcPricer/Heartbeat",
};

std::unique_ptr< GrpcPricer::Stub> GrpcPricer::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< GrpcPricer::Stub> stub(new GrpcPricer::Stub(channel, options));
  return stub;
}

GrpcPricer::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_PriceAndDeltas_(GrpcPricer_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Heartbeat_(GrpcPricer_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status GrpcPricer::Stub::PriceAndDeltas(::grpc::ClientContext* context, const ::PricingInput& request, ::PricingOutput* response) {
  return ::grpc::internal::BlockingUnaryCall< ::PricingInput, ::PricingOutput, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_PriceAndDeltas_, context, request, response);
}

void GrpcPricer::Stub::async::PriceAndDeltas(::grpc::ClientContext* context, const ::PricingInput* request, ::PricingOutput* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::PricingInput, ::PricingOutput, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PriceAndDeltas_, context, request, response, std::move(f));
}

void GrpcPricer::Stub::async::PriceAndDeltas(::grpc::ClientContext* context, const ::PricingInput* request, ::PricingOutput* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PriceAndDeltas_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::PricingOutput>* GrpcPricer::Stub::PrepareAsyncPriceAndDeltasRaw(::grpc::ClientContext* context, const ::PricingInput& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::PricingOutput, ::PricingInput, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_PriceAndDeltas_, context, request);
}

::grpc::ClientAsyncResponseReader< ::PricingOutput>* GrpcPricer::Stub::AsyncPriceAndDeltasRaw(::grpc::ClientContext* context, const ::PricingInput& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPriceAndDeltasRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status GrpcPricer::Stub::Heartbeat(::grpc::ClientContext* context, const ::Empty& request, ::ReqInfo* response) {
  return ::grpc::internal::BlockingUnaryCall< ::Empty, ::ReqInfo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Heartbeat_, context, request, response);
}

void GrpcPricer::Stub::async::Heartbeat(::grpc::ClientContext* context, const ::Empty* request, ::ReqInfo* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::Empty, ::ReqInfo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Heartbeat_, context, request, response, std::move(f));
}

void GrpcPricer::Stub::async::Heartbeat(::grpc::ClientContext* context, const ::Empty* request, ::ReqInfo* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Heartbeat_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ReqInfo>* GrpcPricer::Stub::PrepareAsyncHeartbeatRaw(::grpc::ClientContext* context, const ::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ReqInfo, ::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Heartbeat_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ReqInfo>* GrpcPricer::Stub::AsyncHeartbeatRaw(::grpc::ClientContext* context, const ::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncHeartbeatRaw(context, request, cq);
  result->StartCall();
  return result;
}

GrpcPricer::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      GrpcPricer_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< GrpcPricer::Service, ::PricingInput, ::PricingOutput, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](GrpcPricer::Service* service,
             ::grpc::ServerContext* ctx,
             const ::PricingInput* req,
             ::PricingOutput* resp) {
               return service->PriceAndDeltas(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      GrpcPricer_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< GrpcPricer::Service, ::Empty, ::ReqInfo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](GrpcPricer::Service* service,
             ::grpc::ServerContext* ctx,
             const ::Empty* req,
             ::ReqInfo* resp) {
               return service->Heartbeat(ctx, req, resp);
             }, this)));
}

GrpcPricer::Service::~Service() {
}

::grpc::Status GrpcPricer::Service::PriceAndDeltas(::grpc::ServerContext* context, const ::PricingInput* request, ::PricingOutput* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status GrpcPricer::Service::Heartbeat(::grpc::ServerContext* context, const ::Empty* request, ::ReqInfo* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


