// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pricing.proto

#include "pricing.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = ::PROTOBUF_NAMESPACE_ID::internal;
template <typename>
PROTOBUF_CONSTEXPR PricingInput::PricingInput(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.past_)*/{}
  , /*decltype(_impl_.json_)*/ {
    &::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized {}
  }

  , /*decltype(_impl_.time_)*/ 0

  , /*decltype(_impl_.monitoringdatereached_)*/ false

  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PricingInputDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PricingInputDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PricingInputDefaultTypeInternal() {}
  union {
    PricingInput _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PricingInputDefaultTypeInternal _PricingInput_default_instance_;
template <typename>
PROTOBUF_CONSTEXPR PastLines::PastLines(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.value_)*/ {}

  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PastLinesDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PastLinesDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PastLinesDefaultTypeInternal() {}
  union {
    PastLines _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PastLinesDefaultTypeInternal _PastLines_default_instance_;
template <typename>
PROTOBUF_CONSTEXPR PricingOutput::PricingOutput(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.deltas_)*/ {}

  , /*decltype(_impl_.deltasstddev_)*/ {}

  , /*decltype(_impl_.price_)*/ 0

  , /*decltype(_impl_.pricestddev_)*/ 0

  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PricingOutputDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PricingOutputDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PricingOutputDefaultTypeInternal() {}
  union {
    PricingOutput _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PricingOutputDefaultTypeInternal _PricingOutput_default_instance_;
template <typename>
PROTOBUF_CONSTEXPR Empty::Empty(
    ::_pbi::ConstantInitialized) {}
struct EmptyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EmptyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~EmptyDefaultTypeInternal() {}
  union {
    Empty _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EmptyDefaultTypeInternal _Empty_default_instance_;
template <typename>
PROTOBUF_CONSTEXPR ReqInfo::ReqInfo(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.domesticinterestrate_)*/ 0

  , /*decltype(_impl_.relativefinitedifferencestep_)*/ 0

  , /*decltype(_impl_.samplenb_)*/ 0

  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ReqInfoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ReqInfoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ReqInfoDefaultTypeInternal() {}
  union {
    ReqInfo _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ReqInfoDefaultTypeInternal _ReqInfo_default_instance_;
static ::_pb::Metadata file_level_metadata_pricing_2eproto[5];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_pricing_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_pricing_2eproto = nullptr;
const ::uint32_t TableStruct_pricing_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::PricingInput, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::PricingInput, _impl_.past_),
    PROTOBUF_FIELD_OFFSET(::PricingInput, _impl_.monitoringdatereached_),
    PROTOBUF_FIELD_OFFSET(::PricingInput, _impl_.time_),
    PROTOBUF_FIELD_OFFSET(::PricingInput, _impl_.json_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::PastLines, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::PastLines, _impl_.value_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::PricingOutput, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::PricingOutput, _impl_.price_),
    PROTOBUF_FIELD_OFFSET(::PricingOutput, _impl_.deltas_),
    PROTOBUF_FIELD_OFFSET(::PricingOutput, _impl_.pricestddev_),
    PROTOBUF_FIELD_OFFSET(::PricingOutput, _impl_.deltasstddev_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::Empty, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::ReqInfo, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::ReqInfo, _impl_.domesticinterestrate_),
    PROTOBUF_FIELD_OFFSET(::ReqInfo, _impl_.relativefinitedifferencestep_),
    PROTOBUF_FIELD_OFFSET(::ReqInfo, _impl_.samplenb_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        { 0, -1, -1, sizeof(::PricingInput)},
        { 12, -1, -1, sizeof(::PastLines)},
        { 21, -1, -1, sizeof(::PricingOutput)},
        { 33, -1, -1, sizeof(::Empty)},
        { 41, -1, -1, sizeof(::ReqInfo)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::_PricingInput_default_instance_._instance,
    &::_PastLines_default_instance_._instance,
    &::_PricingOutput_default_instance_._instance,
    &::_Empty_default_instance_._instance,
    &::_ReqInfo_default_instance_._instance,
};
const char descriptor_table_protodef_pricing_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\rpricing.proto\"c\n\014PricingInput\022\030\n\004past\030"
    "\001 \003(\0132\n.PastLines\022\035\n\025monitoringDateReach"
    "ed\030\002 \001(\010\022\014\n\004time\030\003 \001(\001\022\014\n\004json\030\004 \001(\t\"\032\n\t"
    "PastLines\022\r\n\005value\030\001 \003(\001\"Y\n\rPricingOutpu"
    "t\022\r\n\005price\030\001 \001(\001\022\016\n\006deltas\030\002 \003(\001\022\023\n\013pric"
    "eStdDev\030\003 \001(\001\022\024\n\014deltasStdDev\030\004 \003(\001\"\007\n\005E"
    "mpty\"_\n\007ReqInfo\022\034\n\024domesticInterestRate\030"
    "\001 \001(\001\022$\n\034relativeFiniteDifferenceStep\030\002 "
    "\001(\001\022\020\n\010sampleNb\030\003 \001(\0052\\\n\nGrpcPricer\022/\n\016P"
    "riceAndDeltas\022\r.PricingInput\032\016.PricingOu"
    "tput\022\035\n\tHeartbeat\022\006.Empty\032\010.ReqInfoB\025\252\002\022"
    "GrpcPricing.Protosb\006proto3"
};
static ::absl::once_flag descriptor_table_pricing_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_pricing_2eproto = {
    false,
    false,
    466,
    descriptor_table_protodef_pricing_2eproto,
    "pricing.proto",
    &descriptor_table_pricing_2eproto_once,
    nullptr,
    0,
    5,
    schemas,
    file_default_instances,
    TableStruct_pricing_2eproto::offsets,
    file_level_metadata_pricing_2eproto,
    file_level_enum_descriptors_pricing_2eproto,
    file_level_service_descriptors_pricing_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_pricing_2eproto_getter() {
  return &descriptor_table_pricing_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_pricing_2eproto(&descriptor_table_pricing_2eproto);
// ===================================================================

class PricingInput::_Internal {
 public:
};

PricingInput::PricingInput(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:PricingInput)
}
PricingInput::PricingInput(const PricingInput& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PricingInput* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.past_){from._impl_.past_}
    , decltype(_impl_.json_) {}

    , decltype(_impl_.time_) {}

    , decltype(_impl_.monitoringdatereached_) {}

    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.json_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.json_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_json().empty()) {
    _this->_impl_.json_.Set(from._internal_json(), _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.time_, &from._impl_.time_,
    static_cast<::size_t>(reinterpret_cast<char*>(&_impl_.monitoringdatereached_) -
    reinterpret_cast<char*>(&_impl_.time_)) + sizeof(_impl_.monitoringdatereached_));
  // @@protoc_insertion_point(copy_constructor:PricingInput)
}

inline void PricingInput::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_.past_){arena}
    , decltype(_impl_.json_) {}

    , decltype(_impl_.time_) { 0 }

    , decltype(_impl_.monitoringdatereached_) { false }

    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.json_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.json_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

PricingInput::~PricingInput() {
  // @@protoc_insertion_point(destructor:PricingInput)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PricingInput::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  _internal_mutable_past()->~RepeatedPtrField();
  _impl_.json_.Destroy();
}

void PricingInput::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PricingInput::Clear() {
// @@protoc_insertion_point(message_clear_start:PricingInput)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_mutable_past()->Clear();
  _impl_.json_.ClearToEmpty();
  ::memset(&_impl_.time_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.monitoringdatereached_) -
      reinterpret_cast<char*>(&_impl_.time_)) + sizeof(_impl_.monitoringdatereached_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PricingInput::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .PastLines past = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_past(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else {
          goto handle_unusual;
        }
        continue;
      // bool monitoringDateReached = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 16)) {
          _impl_.monitoringdatereached_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // double time = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 25)) {
          _impl_.time_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else {
          goto handle_unusual;
        }
        continue;
      // string json = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_json();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "PricingInput.json"));
        } else {
          goto handle_unusual;
        }
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::uint8_t* PricingInput::_InternalSerialize(
    ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:PricingInput)
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .PastLines past = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_past_size()); i < n; i++) {
    const auto& repfield = this->_internal_past(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  // bool monitoringDateReached = 2;
  if (this->_internal_monitoringdatereached() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        2, this->_internal_monitoringdatereached(), target);
  }

  // double time = 3;
  static_assert(sizeof(::uint64_t) == sizeof(double), "Code assumes ::uint64_t and double are the same size.");
  double tmp_time = this->_internal_time();
  ::uint64_t raw_time;
  memcpy(&raw_time, &tmp_time, sizeof(tmp_time));
  if (raw_time != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(
        3, this->_internal_time(), target);
  }

  // string json = 4;
  if (!this->_internal_json().empty()) {
    const std::string& _s = this->_internal_json();
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE, "PricingInput.json");
    target = stream->WriteStringMaybeAliased(4, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PricingInput)
  return target;
}

::size_t PricingInput::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:PricingInput)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .PastLines past = 1;
  total_size += 1UL * this->_internal_past_size();
  for (const auto& msg : this->_internal_past()) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // string json = 4;
  if (!this->_internal_json().empty()) {
    total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
                                    this->_internal_json());
  }

  // double time = 3;
  static_assert(sizeof(::uint64_t) == sizeof(double), "Code assumes ::uint64_t and double are the same size.");
  double tmp_time = this->_internal_time();
  ::uint64_t raw_time;
  memcpy(&raw_time, &tmp_time, sizeof(tmp_time));
  if (raw_time != 0) {
    total_size += 9;
  }

  // bool monitoringDateReached = 2;
  if (this->_internal_monitoringdatereached() != 0) {
    total_size += 2;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PricingInput::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PricingInput::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PricingInput::GetClassData() const { return &_class_data_; }


void PricingInput::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PricingInput*>(&to_msg);
  auto& from = static_cast<const PricingInput&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:PricingInput)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_past()->MergeFrom(from._internal_past());
  if (!from._internal_json().empty()) {
    _this->_internal_set_json(from._internal_json());
  }
  static_assert(sizeof(::uint64_t) == sizeof(double), "Code assumes ::uint64_t and double are the same size.");
  double tmp_time = from._internal_time();
  ::uint64_t raw_time;
  memcpy(&raw_time, &tmp_time, sizeof(tmp_time));
  if (raw_time != 0) {
    _this->_internal_set_time(from._internal_time());
  }
  if (from._internal_monitoringdatereached() != 0) {
    _this->_internal_set_monitoringdatereached(from._internal_monitoringdatereached());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PricingInput::CopyFrom(const PricingInput& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PricingInput)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PricingInput::IsInitialized() const {
  return true;
}

void PricingInput::InternalSwap(PricingInput* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _internal_mutable_past()->InternalSwap(other->_internal_mutable_past());
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.json_, lhs_arena,
                                       &other->_impl_.json_, rhs_arena);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PricingInput, _impl_.monitoringdatereached_)
      + sizeof(PricingInput::_impl_.monitoringdatereached_)
      - PROTOBUF_FIELD_OFFSET(PricingInput, _impl_.time_)>(
          reinterpret_cast<char*>(&_impl_.time_),
          reinterpret_cast<char*>(&other->_impl_.time_));
}

::PROTOBUF_NAMESPACE_ID::Metadata PricingInput::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_pricing_2eproto_getter, &descriptor_table_pricing_2eproto_once,
      file_level_metadata_pricing_2eproto[0]);
}
// ===================================================================

class PastLines::_Internal {
 public:
};

PastLines::PastLines(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:PastLines)
}
PastLines::PastLines(const PastLines& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PastLines* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.value_) { from._impl_.value_ }

    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:PastLines)
}

inline void PastLines::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_.value_) { arena }

    , /*decltype(_impl_._cached_size_)*/{}
  };
}

PastLines::~PastLines() {
  // @@protoc_insertion_point(destructor:PastLines)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PastLines::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.value_.~RepeatedField();
}

void PastLines::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PastLines::Clear() {
// @@protoc_insertion_point(message_clear_start:PastLines)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_mutable_value()->Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PastLines::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated double value = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 10)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedDoubleParser(_internal_mutable_value(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::uint8_t>(tag) == 9) {
          _internal_add_value(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr));
          ptr += sizeof(double);
        } else {
          goto handle_unusual;
        }
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::uint8_t* PastLines::_InternalSerialize(
    ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:PastLines)
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated double value = 1;
  if (this->_internal_value_size() > 0) {
    target = stream->WriteFixedPacked(1, _internal_value(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PastLines)
  return target;
}

::size_t PastLines::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:PastLines)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated double value = 1;
  {
    std::size_t data_size = std::size_t{8} *
        ::_pbi::FromIntSize(this->_internal_value_size())
    ;
    std::size_t tag_size = data_size == 0
        ? 0
        : 1 + ::_pbi::WireFormatLite::Int32Size(
                            static_cast<int32_t>(data_size))
    ;
    total_size += tag_size + data_size;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PastLines::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PastLines::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PastLines::GetClassData() const { return &_class_data_; }


void PastLines::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PastLines*>(&to_msg);
  auto& from = static_cast<const PastLines&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:PastLines)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.value_.MergeFrom(from._impl_.value_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PastLines::CopyFrom(const PastLines& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PastLines)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PastLines::IsInitialized() const {
  return true;
}

void PastLines::InternalSwap(PastLines* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.value_.InternalSwap(&other->_impl_.value_);
}

::PROTOBUF_NAMESPACE_ID::Metadata PastLines::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_pricing_2eproto_getter, &descriptor_table_pricing_2eproto_once,
      file_level_metadata_pricing_2eproto[1]);
}
// ===================================================================

class PricingOutput::_Internal {
 public:
};

PricingOutput::PricingOutput(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:PricingOutput)
}
PricingOutput::PricingOutput(const PricingOutput& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PricingOutput* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.deltas_) { from._impl_.deltas_ }

    , decltype(_impl_.deltasstddev_) { from._impl_.deltasstddev_ }

    , decltype(_impl_.price_) {}

    , decltype(_impl_.pricestddev_) {}

    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.price_, &from._impl_.price_,
    static_cast<::size_t>(reinterpret_cast<char*>(&_impl_.pricestddev_) -
    reinterpret_cast<char*>(&_impl_.price_)) + sizeof(_impl_.pricestddev_));
  // @@protoc_insertion_point(copy_constructor:PricingOutput)
}

inline void PricingOutput::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_.deltas_) { arena }

    , decltype(_impl_.deltasstddev_) { arena }

    , decltype(_impl_.price_) { 0 }

    , decltype(_impl_.pricestddev_) { 0 }

    , /*decltype(_impl_._cached_size_)*/{}
  };
}

PricingOutput::~PricingOutput() {
  // @@protoc_insertion_point(destructor:PricingOutput)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PricingOutput::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.deltas_.~RepeatedField();
  _impl_.deltasstddev_.~RepeatedField();
}

void PricingOutput::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PricingOutput::Clear() {
// @@protoc_insertion_point(message_clear_start:PricingOutput)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_mutable_deltas()->Clear();
  _internal_mutable_deltasstddev()->Clear();
  ::memset(&_impl_.price_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.pricestddev_) -
      reinterpret_cast<char*>(&_impl_.price_)) + sizeof(_impl_.pricestddev_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PricingOutput::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // double price = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 9)) {
          _impl_.price_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else {
          goto handle_unusual;
        }
        continue;
      // repeated double deltas = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 18)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedDoubleParser(_internal_mutable_deltas(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::uint8_t>(tag) == 17) {
          _internal_add_deltas(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr));
          ptr += sizeof(double);
        } else {
          goto handle_unusual;
        }
        continue;
      // double priceStdDev = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 25)) {
          _impl_.pricestddev_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else {
          goto handle_unusual;
        }
        continue;
      // repeated double deltasStdDev = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 34)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedDoubleParser(_internal_mutable_deltasstddev(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::uint8_t>(tag) == 33) {
          _internal_add_deltasstddev(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr));
          ptr += sizeof(double);
        } else {
          goto handle_unusual;
        }
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::uint8_t* PricingOutput::_InternalSerialize(
    ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:PricingOutput)
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // double price = 1;
  static_assert(sizeof(::uint64_t) == sizeof(double), "Code assumes ::uint64_t and double are the same size.");
  double tmp_price = this->_internal_price();
  ::uint64_t raw_price;
  memcpy(&raw_price, &tmp_price, sizeof(tmp_price));
  if (raw_price != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(
        1, this->_internal_price(), target);
  }

  // repeated double deltas = 2;
  if (this->_internal_deltas_size() > 0) {
    target = stream->WriteFixedPacked(2, _internal_deltas(), target);
  }

  // double priceStdDev = 3;
  static_assert(sizeof(::uint64_t) == sizeof(double), "Code assumes ::uint64_t and double are the same size.");
  double tmp_pricestddev = this->_internal_pricestddev();
  ::uint64_t raw_pricestddev;
  memcpy(&raw_pricestddev, &tmp_pricestddev, sizeof(tmp_pricestddev));
  if (raw_pricestddev != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(
        3, this->_internal_pricestddev(), target);
  }

  // repeated double deltasStdDev = 4;
  if (this->_internal_deltasstddev_size() > 0) {
    target = stream->WriteFixedPacked(4, _internal_deltasstddev(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PricingOutput)
  return target;
}

::size_t PricingOutput::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:PricingOutput)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated double deltas = 2;
  {
    std::size_t data_size = std::size_t{8} *
        ::_pbi::FromIntSize(this->_internal_deltas_size())
    ;
    std::size_t tag_size = data_size == 0
        ? 0
        : 1 + ::_pbi::WireFormatLite::Int32Size(
                            static_cast<int32_t>(data_size))
    ;
    total_size += tag_size + data_size;
  }

  // repeated double deltasStdDev = 4;
  {
    std::size_t data_size = std::size_t{8} *
        ::_pbi::FromIntSize(this->_internal_deltasstddev_size())
    ;
    std::size_t tag_size = data_size == 0
        ? 0
        : 1 + ::_pbi::WireFormatLite::Int32Size(
                            static_cast<int32_t>(data_size))
    ;
    total_size += tag_size + data_size;
  }

  // double price = 1;
  static_assert(sizeof(::uint64_t) == sizeof(double), "Code assumes ::uint64_t and double are the same size.");
  double tmp_price = this->_internal_price();
  ::uint64_t raw_price;
  memcpy(&raw_price, &tmp_price, sizeof(tmp_price));
  if (raw_price != 0) {
    total_size += 9;
  }

  // double priceStdDev = 3;
  static_assert(sizeof(::uint64_t) == sizeof(double), "Code assumes ::uint64_t and double are the same size.");
  double tmp_pricestddev = this->_internal_pricestddev();
  ::uint64_t raw_pricestddev;
  memcpy(&raw_pricestddev, &tmp_pricestddev, sizeof(tmp_pricestddev));
  if (raw_pricestddev != 0) {
    total_size += 9;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PricingOutput::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PricingOutput::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PricingOutput::GetClassData() const { return &_class_data_; }


void PricingOutput::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PricingOutput*>(&to_msg);
  auto& from = static_cast<const PricingOutput&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:PricingOutput)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.deltas_.MergeFrom(from._impl_.deltas_);
  _this->_impl_.deltasstddev_.MergeFrom(from._impl_.deltasstddev_);
  static_assert(sizeof(::uint64_t) == sizeof(double), "Code assumes ::uint64_t and double are the same size.");
  double tmp_price = from._internal_price();
  ::uint64_t raw_price;
  memcpy(&raw_price, &tmp_price, sizeof(tmp_price));
  if (raw_price != 0) {
    _this->_internal_set_price(from._internal_price());
  }
  static_assert(sizeof(::uint64_t) == sizeof(double), "Code assumes ::uint64_t and double are the same size.");
  double tmp_pricestddev = from._internal_pricestddev();
  ::uint64_t raw_pricestddev;
  memcpy(&raw_pricestddev, &tmp_pricestddev, sizeof(tmp_pricestddev));
  if (raw_pricestddev != 0) {
    _this->_internal_set_pricestddev(from._internal_pricestddev());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PricingOutput::CopyFrom(const PricingOutput& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PricingOutput)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PricingOutput::IsInitialized() const {
  return true;
}

void PricingOutput::InternalSwap(PricingOutput* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.deltas_.InternalSwap(&other->_impl_.deltas_);
  _impl_.deltasstddev_.InternalSwap(&other->_impl_.deltasstddev_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PricingOutput, _impl_.pricestddev_)
      + sizeof(PricingOutput::_impl_.pricestddev_)
      - PROTOBUF_FIELD_OFFSET(PricingOutput, _impl_.price_)>(
          reinterpret_cast<char*>(&_impl_.price_),
          reinterpret_cast<char*>(&other->_impl_.price_));
}

::PROTOBUF_NAMESPACE_ID::Metadata PricingOutput::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_pricing_2eproto_getter, &descriptor_table_pricing_2eproto_once,
      file_level_metadata_pricing_2eproto[2]);
}
// ===================================================================

class Empty::_Internal {
 public:
};

Empty::Empty(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena) {
  // @@protoc_insertion_point(arena_constructor:Empty)
}
Empty::Empty(const Empty& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  Empty* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:Empty)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Empty::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Empty::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata Empty::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_pricing_2eproto_getter, &descriptor_table_pricing_2eproto_once,
      file_level_metadata_pricing_2eproto[3]);
}
// ===================================================================

class ReqInfo::_Internal {
 public:
};

ReqInfo::ReqInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ReqInfo)
}
ReqInfo::ReqInfo(const ReqInfo& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(), _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(
      from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:ReqInfo)
}

inline void ReqInfo::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_.domesticinterestrate_) { 0 }

    , decltype(_impl_.relativefinitedifferencestep_) { 0 }

    , decltype(_impl_.samplenb_) { 0 }

    , /*decltype(_impl_._cached_size_)*/{}
  };
}

ReqInfo::~ReqInfo() {
  // @@protoc_insertion_point(destructor:ReqInfo)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ReqInfo::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
}

void ReqInfo::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ReqInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:ReqInfo)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.domesticinterestrate_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.samplenb_) -
      reinterpret_cast<char*>(&_impl_.domesticinterestrate_)) + sizeof(_impl_.samplenb_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ReqInfo::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // double domesticInterestRate = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 9)) {
          _impl_.domesticinterestrate_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else {
          goto handle_unusual;
        }
        continue;
      // double relativeFiniteDifferenceStep = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 17)) {
          _impl_.relativefinitedifferencestep_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else {
          goto handle_unusual;
        }
        continue;
      // int32 sampleNb = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 24)) {
          _impl_.samplenb_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::uint8_t* ReqInfo::_InternalSerialize(
    ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ReqInfo)
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // double domesticInterestRate = 1;
  static_assert(sizeof(::uint64_t) == sizeof(double), "Code assumes ::uint64_t and double are the same size.");
  double tmp_domesticinterestrate = this->_internal_domesticinterestrate();
  ::uint64_t raw_domesticinterestrate;
  memcpy(&raw_domesticinterestrate, &tmp_domesticinterestrate, sizeof(tmp_domesticinterestrate));
  if (raw_domesticinterestrate != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(
        1, this->_internal_domesticinterestrate(), target);
  }

  // double relativeFiniteDifferenceStep = 2;
  static_assert(sizeof(::uint64_t) == sizeof(double), "Code assumes ::uint64_t and double are the same size.");
  double tmp_relativefinitedifferencestep = this->_internal_relativefinitedifferencestep();
  ::uint64_t raw_relativefinitedifferencestep;
  memcpy(&raw_relativefinitedifferencestep, &tmp_relativefinitedifferencestep, sizeof(tmp_relativefinitedifferencestep));
  if (raw_relativefinitedifferencestep != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(
        2, this->_internal_relativefinitedifferencestep(), target);
  }

  // int32 sampleNb = 3;
  if (this->_internal_samplenb() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(
        3, this->_internal_samplenb(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ReqInfo)
  return target;
}

::size_t ReqInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ReqInfo)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // double domesticInterestRate = 1;
  static_assert(sizeof(::uint64_t) == sizeof(double), "Code assumes ::uint64_t and double are the same size.");
  double tmp_domesticinterestrate = this->_internal_domesticinterestrate();
  ::uint64_t raw_domesticinterestrate;
  memcpy(&raw_domesticinterestrate, &tmp_domesticinterestrate, sizeof(tmp_domesticinterestrate));
  if (raw_domesticinterestrate != 0) {
    total_size += 9;
  }

  // double relativeFiniteDifferenceStep = 2;
  static_assert(sizeof(::uint64_t) == sizeof(double), "Code assumes ::uint64_t and double are the same size.");
  double tmp_relativefinitedifferencestep = this->_internal_relativefinitedifferencestep();
  ::uint64_t raw_relativefinitedifferencestep;
  memcpy(&raw_relativefinitedifferencestep, &tmp_relativefinitedifferencestep, sizeof(tmp_relativefinitedifferencestep));
  if (raw_relativefinitedifferencestep != 0) {
    total_size += 9;
  }

  // int32 sampleNb = 3;
  if (this->_internal_samplenb() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_samplenb());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ReqInfo::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ReqInfo::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ReqInfo::GetClassData() const { return &_class_data_; }


void ReqInfo::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ReqInfo*>(&to_msg);
  auto& from = static_cast<const ReqInfo&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ReqInfo)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  static_assert(sizeof(::uint64_t) == sizeof(double), "Code assumes ::uint64_t and double are the same size.");
  double tmp_domesticinterestrate = from._internal_domesticinterestrate();
  ::uint64_t raw_domesticinterestrate;
  memcpy(&raw_domesticinterestrate, &tmp_domesticinterestrate, sizeof(tmp_domesticinterestrate));
  if (raw_domesticinterestrate != 0) {
    _this->_internal_set_domesticinterestrate(from._internal_domesticinterestrate());
  }
  static_assert(sizeof(::uint64_t) == sizeof(double), "Code assumes ::uint64_t and double are the same size.");
  double tmp_relativefinitedifferencestep = from._internal_relativefinitedifferencestep();
  ::uint64_t raw_relativefinitedifferencestep;
  memcpy(&raw_relativefinitedifferencestep, &tmp_relativefinitedifferencestep, sizeof(tmp_relativefinitedifferencestep));
  if (raw_relativefinitedifferencestep != 0) {
    _this->_internal_set_relativefinitedifferencestep(from._internal_relativefinitedifferencestep());
  }
  if (from._internal_samplenb() != 0) {
    _this->_internal_set_samplenb(from._internal_samplenb());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ReqInfo::CopyFrom(const ReqInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ReqInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ReqInfo::IsInitialized() const {
  return true;
}

void ReqInfo::InternalSwap(ReqInfo* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ReqInfo, _impl_.samplenb_)
      + sizeof(ReqInfo::_impl_.samplenb_)
      - PROTOBUF_FIELD_OFFSET(ReqInfo, _impl_.domesticinterestrate_)>(
          reinterpret_cast<char*>(&_impl_.domesticinterestrate_),
          reinterpret_cast<char*>(&other->_impl_.domesticinterestrate_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ReqInfo::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_pricing_2eproto_getter, &descriptor_table_pricing_2eproto_once,
      file_level_metadata_pricing_2eproto[4]);
}
// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::PricingInput*
Arena::CreateMaybeMessage< ::PricingInput >(Arena* arena) {
  return Arena::CreateMessageInternal< ::PricingInput >(arena);
}
template<> PROTOBUF_NOINLINE ::PastLines*
Arena::CreateMaybeMessage< ::PastLines >(Arena* arena) {
  return Arena::CreateMessageInternal< ::PastLines >(arena);
}
template<> PROTOBUF_NOINLINE ::PricingOutput*
Arena::CreateMaybeMessage< ::PricingOutput >(Arena* arena) {
  return Arena::CreateMessageInternal< ::PricingOutput >(arena);
}
template<> PROTOBUF_NOINLINE ::Empty*
Arena::CreateMaybeMessage< ::Empty >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Empty >(arena);
}
template<> PROTOBUF_NOINLINE ::ReqInfo*
Arena::CreateMaybeMessage< ::ReqInfo >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ReqInfo >(arena);
}
PROTOBUF_NAMESPACE_CLOSE
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
